### ISSUE TITLE
undefined: sqlite3.ErrNoExtended

### ISSUE THREAD

**Issue by the122** [CharlesDardaman/blueskyfirehose#3]
Trying to run the code, cmd is ran as admin, default .zip extracted, 
![image](https://github.com/CharlesDardaman/blueskyfirehose/assets/70115491/5d408429-77d9-47e0-b8d0-27841304f08b)
Error occurs on verification attempt as well, it may well be an issue with my config, but I'm not familiar with Go at all

**Comment by realsigridjin** [comment]
hey the fix was merged from the `gorm/sqlite` package four months ago. see [here](https://github.com/go-gorm/sqlite/issues/142)

**Comment by CharlesDardaman** [comment]
Increased the version, in the most recent [commit](https://github.com/CharlesDardaman/blueskyfirehose/commit/c2fe4dc71c0b421e7ce6a63d93afc57fa65a07b8). I am unable to replicate the issue in the current state. Please let me know if you are still having issues running the code.
